<a href="https://colab.research.google.com/github/dipikachavan06/data_science_lab/blob/main/experiment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Our 3x3 matrix:")
print(matrix)

# Compute its determinant
determinant = np.linalg.det(matrix)
print(f"\nThe determinant of the matrix is: {determinant}")

Our 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The determinant of the matrix is: 0.0


Now, let's try to find the inverse of the matrix using `np.linalg.inv()`.

In [3]:
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("The inverse of the matrix is:")
    print(inverse_matrix)
except np.linalg.LinAlgError as e:
    print(f"Error: {e}. This matrix might be singular and does not have an inverse.")

Error: Singular matrix. This matrix might be singular and does not have an inverse.


To solve the system of linear equations:

2x + 3y = 10
4x + 5y = 20

We can represent this system in matrix form as `Ax = B`, where:

`A` is the coefficient matrix: `[[2, 3], [4, 5]]`
`x` is the variable vector: `[x, y]`
`B` is the constant vector: `[10, 20]`

We'll use `numpy.linalg.solve(A, B)` to find the values of `x` and `y`.

In [4]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3],
              [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of linear equations
x_and_y = np.linalg.solve(A, B)

print("The solution to the system of equations is:")
print(f"x = {x_and_y[0]}")
print(f"y = {x_and_y[1]}")

The solution to the system of equations is:
x = 5.0
y = 0.0
